# Generated by Django 5.0.1 on 2024-02-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
    ]
