# Generated by Django 5.0.1 on 2024-02-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20240208_2000'),
    ]

    operations = [
    ]
