# Generated by Django 5.0.1 on 2024-02-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20240209_0925'),
    ]

    operations = [
    ]
